### ISSUE TITLE
Issues running eval.py and building pyflow

### ISSUE THREAD

**Issue by mwalczyk** [alterzero/RBPN-PyTorch#15]
Hi,
I'm trying to run the `eval.py` script with all of the default command-line arguments and have been experiencing a couple of (inter-related?) issues.

The `pyflow` folder included in the repository doesn't build for me, out-of-the-box. I ran into issues due to the fact that all of the `.cpp` files are missing (which exist in the official `pyflow` repo). After re-cloning this repo, I was able to build `pyflow`. 

However, when running the provided `eval.py` script, I then get the following error:
```
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/code/pytorch_projects/upres/rbpn/rbpn.py", line 76, in forward
    feat_frame.append(self.feat1(torch.cat((x, neigbor[j], flow[j]),1)))
RuntimeError: Expected a Tensor of type torch.cuda.FloatTensor but found a type torch.cuda.DoubleTensor for sequence element 2  in sequence argument at position #1 'tensors'
```
I was able to get around this by modifying line #76 of `rbpn.py` to include an explicit cast to a floating-point tensor as follows:
```
feat_frame.append(self.feat1(torch.cat((x, neigbor[j], flow[j].float()),1)))
```
After this change, the code runs, but there are continuous error messages of the form:
```
All the pixels are invalid in estimation Laplacian noise!!!
Something severely wrong happened!!!
```
The code finishes execution and outputs into the `Results/` folder. However, all of these images are the same as the original resolution (720 x 480), so it would seem that the up-resolution code didn't actually do anything. 

I know this is a lot, but any ideas of what I might be doing wrong? Thanks in advance.

**Comment by alterzero** [comment]
Hi, I have added .float() in the eval.py. 
https://github.com/alterzero/RBPN-PyTorch/blob/6424b65b4fcaeeb321e840f3b4ec533f679a4396/eval.py#L82

Pyflow requires python 3.5. Do you use python 3.5?

The evaluation code "eval.py" is used to compare the result with the ground truth (GT).
The "data_dir" in the eval.py is refer to the GT frames, which is later downscaled to produce input LR frames.
But, you can modify this a bit, so that no downscaling process is executed.
The easiest way, i think, is to remove the "resize" in the load_img function inside dataset.py
